package com.quarks0.dofusorganizer;


import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.widget.ExpandableListView;
import android.widget.ExpandableListView.OnChildClickListener;
import android.widget.ExpandableListView.OnGroupClickListener;
import android.widget.ExpandableListView.OnGroupCollapseListener;
import android.widget.ExpandableListView.OnGroupExpandListener;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class HarvestTracker extends AppCompatActivity {

    ExpandableListAdapter eHList;
    ExpandableListView eHListView;
    List<String> listHeader;
    HashMap<String,List<String>> listChild;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_harvest_tracker);
        eHListView = (ExpandableListView) findViewById(R.id.eternalHarvestList);
        initiateList();
        eHList = new ExpandableListAdapter(this, listHeader,listChild);
        eHListView.setAdapter(eHList);

        eHListView.setOnGroupClickListener(new OnGroupClickListener() {
            @Override
            public boolean onGroupClick(ExpandableListView parent, View v, int groupPosition, long id) {
                return false;
            }
        });

        eHListView.setOnGroupCollapseListener(new OnGroupCollapseListener() {
            @Override
            public void onGroupCollapse(int groupPosition) {
                Toast.makeText(getApplicationContext(), listHeader.get(groupPosition) + " collapsed", Toast.LENGTH_SHORT).show();
            }
        });

        eHListView.setOnChildClickListener(new OnChildClickListener() {
            @Override
            public boolean onChildClick(ExpandableListView parent, View v, int groupPosition, int childPosition, long id) {
                return false;
            }
        });

        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
    }

    private void initiateList() { //Populates the EH list
        listHeader = new ArrayList<String>();
        listChild = new HashMap<String,List<String>>();

        //Parent menu
        for(int i=0; i<35;i++) {
            listHeader.add("Step "+i);
        }

        //Child menus
        List<String> step1 = new ArrayList<String>();
        step1.add("Grey Mouse");
        step1.add("Moskito");
        step1.add("Arachnee");
        step1.add("White Gobbly");
        step1.add("Black Gobbly");
        step1.add("Evil Tofu");
        step1.add("Sick Arachnee");
        step1.add("Blue Piwi");
        step1.add("Red Piwi");
        step1.add("Yellow Piwi");
        step1.add("Green Piwi");
        step1.add("Purple Piwi");
        step1.add("Air Spark");
        step1.add("Water Spark");
        step1.add("Fire Spark");
        step1.add("Earth Spark");
        step1.add("Blue Larva");
        step1.add("Crab");
        step1.add("Pink Piwi");
        step1.add("Tofu");
        int step1counter = 0;
        int step1max = step1.size();

        List<String> step2 = new ArrayList<String>();
        step1.add("Grey Mouse");
        step1.add("Moskito");
        step1.add("Arachnee");
        step1.add("White Gobbly");
        step1.add("Black Gobbly");
        step1.add("Evil Tofu");
        step1.add("Sick Arachnee");
        step1.add("Blue Piwi");
        step1.add("Red Piwi");
        step1.add("Yellow Piwi");
        step1.add("Green Piwi");
        step1.add("Purple Piwi");
        step1.add("Air Spark");
        step1.add("Water Spark");
        step1.add("Fire Spark");
        step1.add("Earth Spark");
        step1.add("Blue Larva");
        step1.add("Crab");
        step1.add("Pink Piwi");
        step1.add("Tofu");
        int step2counter = 0;
        int step2max = step2.size();

        List<String> step3 = new ArrayList<String>();
        step1.add("Kokonut");
        step1.add("Tikoko");
        step1.add("Glukoko");
        step1.add("Boar");
        step1.add("Green Spimush");
        step1.add("Pumpkwin");
        step1.add("Vampyre");
        step1.add("Coco Biblop");
        step1.add("Morello Cherry Biblop");
        step1.add("Indigo Biblop");
        step1.add("Pippin Biblop");
        step1.add("Karne Rider");
        step1.add("Sick Grossewer Milirat");
        step1.add("Mushd");
        step1.add("Prespic");
        step1.add("Piglet");
        step1.add("Yellow Turtle");
        step1.add("Wabbit");
        step1.add("Gobbal War Chief");
        step1.add("Lousy Pig Shepherd");
        int step3counter = 0;
        int step3max = step3.size();

        List<String> step4 = new ArrayList<String>();
        step1.add("Whitish Fang");
        step1.add("Bulbamboo");
        step1.add("Blue Turtle");
        step1.add("Crow");
        step1.add("Starfish Trooper");
        step1.add("White Snapper");
        step1.add("Blue Snapper");
        step1.add("Orange Snapper");
        step1.add("Green Snapper");
        step1.add("Bambooto");
        step1.add("Red Turtle");
        step1.add("Vampyre Master");
        step1.add("Minoskito");
        step1.add("Neye");
        step1.add("Miliboowolf");
        step1.add("Ambusher");
        step1.add("Bulbiflor");
        step1.add("Green Turtle");
        step1.add("Bwork Magus");
        step1.add("Furious Whitish Fang");
        int step4counter = 0;
        int step4max = step4.size();

        List<String> step5 = new ArrayList<String>();
        step1.add("Dark Rose");
        step1.add("Black Wabbit");
        step1.add("Dark Miner");
        step1.add("Bwork Archer");
        step1.add("Blue Spimush");
        step1.add("Brown Spimush");
        step1.add("Red Spimush");
        step1.add("Crackrock");
        step1.add("Manderisha");
        step1.add("Kitsou Nakwa");
        step1.add("Gargoyl");
        step1.add("Wild Almond Dragoturkey");
        step1.add("Strawberry Jelly");
        step1.add("Skeleton Wabbit");
        step1.add("Invisible Chafer");
        step1.add("Crackler");
        step1.add("Bwork");
        step1.add("Treechnid");
        step1.add("Khamelrost");
        int step5counter = 0;
        int step5max = step5.size();

        List<String> step6 = new ArrayList<String>();
        step1.add("White Scaraleaf");
        step1.add("Blue Scaraleaf");
        step1.add("Red Scaraleaf");
        step1.add("Green Scaraleaf");
        step1.add("Rib");
        step1.add("Coco Blop");
        step1.add("Morello Cherry Blop");
        step1.add("Indigo Blop");
        step1.add("Pippin Blop");
        step1.add("Farle's Pig");
        step1.add("Scaratos");
        step1.add("Boomba");
        step1.add("Trunknid");
        step1.add("Chafter Foot Soldier");
        step1.add("Kloon Snapper");
        step1.add("Treechnee");
        step1.add("Chafer");
        step1.add("Crocodyl");
        step1.add("Sick Grossewer Rat");
        step1.add("Scurvion");
        int step6counter = 0;
        int step6max = step6.size();

        List<String> step7 = new ArrayList<String>();
        step1.add("Wild Ginger Dragoturkey");
        step1.add("Dark Smith");
        step1.add("Kurasso Craboral");
        step1.add("Mahlibuh Craboral");
        step1.add("Mojeeto Craboral");
        step1.add("Passaoh Craboral");
        step1.add("Bulbush");
        step1.add("Major Arachnee");
        step1.add("Araknawa");
        step1.add("Gwandpa Wabbit");
        step1.add("Wo Wabbit");
        step1.add("Lousy Pig Knight");
        step1.add("Aboub");
        step1.add("Amlub");
        step1.add("Codem");
        step1.add("Gink");
        step1.add("Kirevam");
        step1.add("Let Emoliug");
        step1.add("Nebgib");
        step1.add("Nipul");
        int step7counter = 0;
        int step7max = step7.size();

        List<String> step8 = new ArrayList<String>();
        step1.add("Osurc");
        step1.add("Susej");
        step1.add("Kokoko");
        step1.add("Chafer Archer");
        step1.add("Chafer Lancer");
        step1.add("Dok Alako");
        step1.add("Immature Koalak");
        step1.add("Minokid");
        step1.add("Grossewer Shaman");
        step1.add("Boggedown Ouassingue");
        step1.add("Ouassingal");
        step1.add("Ouassingue");
        step1.add("Mahlibuh Palmflower");
        step1.add("Mojeeto Palmflower");
        step1.add("Passaoh Palmflower");
        step1.add("Plain Boar");
        step1.add("Venerable Treechnid");
        step1.add("Plain Crackler");
        step1.add("Pandit");
        step1.add("Elite Chafter");
        int step8counter = 0;
        int step8max = step8.size();

        List<String> step9 = new ArrayList<String>();
        step1.add("Fungi Master");
        step1.add("Polished Crackrock");
        step1.add("Pandikaze");
        step1.add("Kanniballbo");
        step1.add("Kanniball Jav");
        step1.add("Kanniball Sarbak");
        step1.add("Kanniball Thierry");
        step1.add("Drunken Pandalette");
        step1.add("Grossewer Rat");
        step1.add("Kurasso Palmflower");
        step1.add("Ouginak");
        step1.add("Immature White Dreggon");
        step1.add("Immature Golden Dreggon");
        step1.add("Immature Black Dreggon");
        step1.add("Immature Sapphire Dreggon");
        step1.add("White Dragoss");
        step1.add("Golden Dragoss");
        step1.add("Black Dragoss");
        step1.add("Sapphire Dragoss");
        step1.add("Leopardo");
        int step9counter = 0;
        int step9max = step9.size();

        List<String> step10 = new ArrayList<String>();
        step1.add("Quetsnakiatl");
        step1.add("Coralator");
        step1.add("Kitsou Nae");
        step1.add("Raul Mops");
        step1.add("Drunken Pandawa");
        step1.add("Grass Snake");
        step1.add("Explosive Shell");
        step1.add("Cannon Dorf");
        step1.add("Hazwonarm");
        step1.add("Blodz Uker");
        step1.add("White Dreggon");
        step1.add("Golden Dreggon");
        step1.add("Black Dreggon");
        step1.add("Sapphire Dreggon");
        step1.add("Coco Koalak");
        step1.add("Morello Cherry Koalak");
        step1.add("Indigo Koalak");
        step1.add("Pippin Koalak");
        step1.add("Hyoactive Rat");
        step1.add("Sparo");
        int step10counter = 0;
        int step10max = step10.size();

        List<String> step11 = new ArrayList<String>();
        step1.add("Warguerite");
        step1.add("Apero Ghost");
        step1.add("Burning Ghost");
        step1.add("Arepo Ghost");
        step1.add("Brave Ghost");
        step1.add("Dorgan Ation");
        step1.add("Barbrossa");
        step1.add("Ze Flib");
        step1.add("Gwass");
        step1.add("Crocodyl Chief");
        step1.add("Plissken");
        step1.add("Kaniger");
        step1.add("Plain Pikoko");
        step1.add("Polished Crackler");
        step1.add("Mufafah");
        step1.add("Boowolf");
        step1.add("Pandulum");
        step1.add("Kido");
        step1.add("Kilibriss");
        step1.add("Alert White Dreggon");
        int step11counter = 0;
        int step11max = step11.size();

        List<String> step12 = new ArrayList<String>();
        step1.add("Alert Golden Dreggon");
        step1.add("Alert Black Dreggon");
        step1.add("Alert Sapphire Dreggon");
        step1.add("Dragostess");
        step1.add("Koalak Warrior");
        step1.add("Poacher");
        step1.add("Oni");
        step1.add("Brown Warko");
        step1.add("Kitsou Nere");
        step1.add("Dark Treechnid");
        step1.add("Bulbig");
        step1.add("Koalak Gravedigger");
        step1.add("Koalak Forester");
        step1.add("Piralak");
        step1.add("Fisheralak");
        step1.add("Greedovore");
        step1.add("Dark Treechnee");
        step1.add("Wild Golden Dragoturkey");
        step1.add("Koalak Rider");
        step1.add("Moopet");
        int step12counter = 0;
        int step12max = step12.size();

        List<String> step13 = new ArrayList<String>();
        step1.add("Holy Bambooto");
        step1.add("Dreggon Warrior");
        step1.add("Flying Dreggon");
        step1.add("Aeroktor the Warrior");
        step1.add("Aquabralak the Warrior");
        step1.add("Ignilicrobur the Warrior");
        step1.add("Terrakubiack the Warrior");
        step1.add("Zoth Disciple");
        step1.add("Rotaflor");
        step1.add("Bloody Koalak");
        step1.add("Dark Pikoko");
        step1.add("Floramor");
        step1.add("Barkritter");
        step1.add("Wild Koalak");
        step1.add("Mama Koalak");
        step1.add("Koalak Mummy");
        step1.add("Miremop");
        step1.add("Purple Warko");
        step1.add("Zoth Girl");
        step1.add("Zoth Warrior");
        int step13counter = 0;
        int step13max = step13.size();

        List<String> step14 = new ArrayList<String>();
        step1.add("Mopeat");
        step1.add("Dark Treeckler");
        step1.add("Alert White Dragoss");
        step1.add("Alert Golden Dragoss");
        step1.add("Alert Black Dragoss");
        step1.add("Alert Sapphire Dragoss");
        step1.add("Soryo Firefoux");
        step1.add("Kitsou Nufeu");
        step1.add("Maho Firefoux");
        step1.add("Drakoalak");
        step1.add("Reapalak");
        step1.add("Koalak Master");
        step1.add("Cheeken");
        step1.add("Ignirkocropos the Famished");
        step1.add("Terraburkahl the Perdifious");
        step1.add("Aerogoburius the Malicious");
        step1.add("Aqualikros the Merciless");
        step1.add("Trool");
        int step14counter = 0;
        int step14max = step14.size();

        List<String> step15 = new ArrayList<String>();
        step1.add(" Zoth Sergeant");
        step1.add("Snailmet");
        step1.add("Air Pikoko");
        step1.add("Light Treeckler");
        step1.add("Zoth Master");
        step1.add("Mushnid");
        step1.add("Yokai Firefoux ");
        step1.add("Trumperelle");
        step1.add("Mushmunch");
        step1.add("Leopardo Ghost");
        step1.add("Pandikaze Ghost");
        step1.add("Mush Tup");
        step1.add("Mush Rhume");
        step1.add("Mush Mish");
        step1.add("Pandulum Ghost");
        step1.add("Soryo Firefoux Ghost");
        step1.add("Pandora");
        step1.add("Mopy King");
        step1.add("Maho Firefoux Ghost");
        step1.add("Yokai Firefoux Ghost");
        int step15counter = 0;
        int step15max = step15.size();

        List<String> step16 = new ArrayList<String>();
        step1.add("Pandora Ghost");
        step1.add("Tanukouï San Ghost");
        int step16counter = 0;
        int step16max = step16.size();

        List<String> step17 = new ArrayList<String>();
        step1.add("Sponge Mob");
        step1.add("Royal Gobball");
        step1.add("Famished Sunflower");
        step1.add("Royal Blue Jelly");
        step1.add("Shin Larva");
        step1.add("GM Wabbit");
        step1.add("Golden Scarabugly");
        step1.add("Bworkette");
        step1.add("Dragon Pig");
        step1.add("Mumminotor");
        step1.add("Deminoball");
        step1.add("Royal Mint Jelly");
        step1.add("Royal Tofu");
        step1.add("Royal Coco Blop");
        step1.add("Royal Morello Cherry Blop");
        step1.add("Royal Indigo Blop");
        step1.add("Royal Pippin Blop");
        step1.add("Black Rat");
        step1.add("White Rat");
        step1.add("Minotoror");
        int step17counter = 0;
        int step17max = step17.size();

        List<String> step18 = new ArrayList<String>();
        step1.add("Hell Mina");
        step1.add("Tanukouï San");
        step1.add("Legendary Crackler");
        step1.add("Sewer Keeper");
        step1.add("Royal Strawberry Jelly");
        step1.add("Lord Crow");
        step1.add("Royal Rainbow Blop");
        step1.add("Great Coralator");
        step1.add("Gourlo the Terrible");
        step1.add("Moowolf");
        step1.add("Wa Wabbit");
        step1.add("Moon");
        step1.add("Koolich");
        step1.add("Skeunk");
        step1.add("Ancestral Treechnid");
        step1.add("Pandora Master");
        step1.add("Stunned Tynril");
        step1.add("Dismayed Tynril");
        step1.add("Disconcerted Tynril");
        step1.add("Perfidious Tynril");
        int step18counter = 0;
        int step18max = step18.size();

//        List<String> step19 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step19counter = 0;
//        int step19max = step19.size();

//       List<String> step20 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step20counter = 0;
//        int step20max = step20.size();

//       List<String> step21 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step21counter = 0;
//        int step21max = step21.size();

//       List<String> step22 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step22counter = 0;
//        int step22max = step22.size();

        //       List<String> step23 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step23counter = 0;
//        int step23max = step23.size();

        //       List<String> step24 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step24counter = 0;
//        int step24max = step24.size();

        //       List<String> step25 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step25counter = 0;
//        int step25max = step25.size();

        //       List<String> step26 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step26counter = 0;
//        int step26max = step26.size();

        //       List<String> step27 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step27counter = 0;
//        int step27max = step27.size();

        //       List<String> step28 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step28counter = 0;
//        int step28max = step28.size();

        //       List<String> step29 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step29counter = 0;
//        int step29max = step29.size();

        //       List<String> step30 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step30counter = 0;
//        int step30max = step30.size();

        //       List<String> step31 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step31counter = 0;
//        int step31max = step3.size();

        //       List<String> step32 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step32counter = 0;
//        int step32max = step32.size();

        //       List<String> step33 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step33counter = 0;
//        int step33max = step33.size();

        //       List<String> step34 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step34counter = 0;
//        int step34max = step34.size();

        //       List<String> step35 = new ArrayList<String>();
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        step1.add("");
//        int step35counter = 0;
//        int step35max = step35.size();

        //Hooboy, now put them together
        listChild.put(listHeader.get(0),step1);
        listChild.put(listHeader.get(1),step2);
        listChild.put(listHeader.get(2),step3);
        listChild.put(listHeader.get(3),step4);
        listChild.put(listHeader.get(4),step5);
        listChild.put(listHeader.get(5),step6);
        listChild.put(listHeader.get(6),step7);
        listChild.put(listHeader.get(7),step8);
        listChild.put(listHeader.get(8),step9);
        listChild.put(listHeader.get(9),step10);
        listChild.put(listHeader.get(10),step11);
        listChild.put(listHeader.get(11),step12);
        listChild.put(listHeader.get(12),step13);
        listChild.put(listHeader.get(13),step14);
        listChild.put(listHeader.get(14),step15);
        listChild.put(listHeader.get(15),step16);
        listChild.put(listHeader.get(16),step17);
        listChild.put(listHeader.get(17),step18);

    }

}
